# Generated by Django 3.2.14 on 2022-08-18 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_consultant', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('pre_requis', models.TextField(default='', max_length=10000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expires_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Competance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Thematique_metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='media')),
                ('thematique_metier', models.ManyToManyField(related_name='partenaire', to='api.Thematique_metier')),
            ],
        ),
        migrations.CreateModel(
            name='Info_entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='media')),
                ('valeur_humaine', models.TextField()),
                ('secteur', models.CharField(max_length=255)),
                ('problematique', models.TextField()),
                ('project', models.TextField(blank=True)),
                ('user', models.ManyToManyField(related_name='info_entrepreneur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info_consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='media')),
                ('experiences', models.IntegerField()),
                ('valeur_humaine', models.TextField()),
                ('localisation', models.TextField()),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=5)),
                ('competances', models.ManyToManyField(related_name='info_consultant', to='api.Competance')),
                ('user', models.ManyToManyField(related_name='info_consultant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponctualite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('respect', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qualite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commentaire', models.TextField()),
                ('atelier', models.ManyToManyField(related_name='avis', to='api.Atelier')),
                ('user', models.ManyToManyField(related_name='avis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atelier',
            name='creator',
            field=models.ManyToManyField(related_name='atelier', to='api.Info_consultant'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='atelier', to='api.Info_entrepreneur'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='thematique_metier',
            field=models.ManyToManyField(related_name='atelier', to='api.Thematique_metier'),
        ),
    ]
