# Generated by Django 4.0.6 on 2022-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=240)),
                ('prenomClient', models.CharField(max_length=240)),
                ('emailClient', models.EmailField(max_length=254)),
                ('mobileClient', models.CharField(max_length=20)),
                ('passwordClient', models.CharField(max_length=240)),
                ('inscriptionClient', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
