# Generated by Django 4.0.6 on 2022-08-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_consultant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='info_entrepreneur',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
