# Generated by Django 3.2.14 on 2022-08-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_consultant',
            name='competances',
            field=models.ManyToManyField(blank=True, related_name='info_consultant', to='api.Competance'),
        ),
        migrations.AlterField(
            model_name='info_consultant',
            name='experiences',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='info_consultant',
            name='localisation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info_consultant',
            name='tarif',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='info_consultant',
            name='valeur_humaine',
            field=models.TextField(blank=True),
        ),
    ]
