# Generated by Django 4.0.6 on 2022-08-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_info_consultant_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='atelier',
            name='thematique_metier',
            field=models.ManyToManyField(related_name='atelier', to='api.thematique_metier'),
        ),
        migrations.RemoveField(
            model_name='info_consultant',
            name='competances',
        ),
        migrations.AddField(
            model_name='info_consultant',
            name='competances',
            field=models.ManyToManyField(related_name='info_consultant', to='api.competance'),
        ),
    ]
