# Generated by Django 3.2.14 on 2022-08-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220826_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atelier',
            name='annulation_date',
        ),
        migrations.AlterField(
            model_name='atelier',
            name='expires_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='avis',
            name='atelier',
            field=models.ManyToManyField(blank=True, related_name='avis', to='api.Atelier'),
        ),
        migrations.AlterField(
            model_name='info_consultant',
            name='experiences',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info_consultant',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
