# Generated by Django 3.2.14 on 2022-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220826_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='info_consultant',
            field=models.ManyToManyField(related_name='avis', to='api.Info_consultant'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='expires_date',
            field=models.DateTimeField(),
        ),
    ]
