# Generated by Django 3.2.14 on 2022-08-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_competance_alter_atelier_thematique_metier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_consultant',
            name='thematique',
        ),
    ]
