# Generated by Django 3.2.14 on 2022-08-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220829_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_avertissé',
            new_name='is_averti',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_banned',
            new_name='is_interdit',
        ),
    ]
